/* Tables */
CREATE TABLE STANZA (
    CodS INTEGER NOT NULL,
    Piano INTEGER NOT NULL,
    Superficie INTEGER NOT NULL,
    Type INTEGER NOT NULL,
    PRIMARY KEY (CodS)
);
CREATE TABLE AGENZIA (
    CodA INTEGER NOT NULL,
    NTel INTEGER NOT NULL,
    SitoWeb INTEGER,
    Numero_Indirizzo INTEGER NOT NULL,
    Via_Indirizzo INTEGER NOT NULL,
    CAP_Indirizzo INTEGER NOT NULL,
    Citta_Indirizzo INTEGER NOT NULL,
    Stato_Indirizzo INTEGER NOT NULL,
    PRIMARY KEY (CodA)
);
CREATE TABLE PRENOTAZIONE (
    STANZA_CodS INTEGER NOT NULL,
    AGENZIA_CodA INTEGER NOT NULL,
    DataInizio INTEGER NOT NULL,
    DataFine INTEGER NOT NULL,
    PrezzoG INTEGER NOT NULL,
    PRIMARY KEY (STANZA_CodS, AGENZIA_CodA, DataInizio),
    FOREIGN KEY (STANZA_CodS) REFERENCES STANZA(CodS),
    ON DELETE NO ACTION,
    ON UPDATE NO ACTION,
    FOREIGN KEY (AGENZIA_CodA) REFERENCES AGENZIA(CodA),
    ON DELETE NO ACTION,
    ON UPDATE NO ACTION
);
CREATE TABLE HAS_OPTIONAL (
    OPTIONAL_Optional INTEGER NOT NULL,
    STANZA_CodS INTEGER NOT NULL,
    PRIMARY KEY (OPTIONAL_Optional, STANZA_CodS),
    FOREIGN KEY (STANZA_CodS) REFERENCES STANZA(CodS),
    ON DELETE NO ACTION,
    ON UPDATE NO ACTION
);
CREATE TABLE HAS_SPAZIDISPONIBILI (
    SPAZIDISPONIBILI_SpaziDisponibili INTEGER NOT NULL,
    STANZA_CodS INTEGER NOT NULL,
    PRIMARY KEY (SPAZIDISPONIBILI_SpaziDisponibili, STANZA_CodS),
    FOREIGN KEY (STANZA_CodS) REFERENCES STANZA(CodS),
    ON DELETE NO ACTION,
    ON UPDATE NO ACTION
);